const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vp=require('../scripts/lib/viewport.cjs');
test('viewport profiles validate before side effects and restore original-session declared baseline after failures',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'dol-viewport-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const plan={schemaVersion:1,baseline:'none',scope:'#fixture',profiles:[{name:'phone',width:360,height:640,deviceScaleFactor:1,mobile:false},{name:'tablet',width:800,height:1000,deviceScaleFactor:1,mobile:false}]},loaded={plan,sha256:'a'.repeat(64)};
 assert.throws(()=>vp.validate({...plan,baseline:'custom'}));assert.throws(()=>vp.validate({...plan,profiles:[{...plan.profiles[0],deviceScaleFactor:10}]}));
 const calls=[];const client={send:async method=>{calls.push(method);if(method==='Emulation.setDeviceMetricsOverride'){const initial=JSON.parse(fs.readFileSync(path.join(root,'run/manifest.json')));assert.equal(initial.captureEnd,undefined);assert.equal(initial.cleanup[0].status,'unknown');throw Error('PRIVATE_ERROR')}},evaluate:async()=>({width:1000,height:800,devicePixelRatio:1}),close:()=>calls.push('close')};
 const result=await vp.run({endpoint:'http://127.0.0.1:1',out:path.join(root,'run'),testEnvironment:true,exclusiveMetrics:true},loaded,{connect:async()=>client});assert.equal(result.status,'failed');assert.equal(result.cleanup[0].status,'acknowledged');assert.ok(calls.includes('Emulation.clearDeviceMetricsOverride'));assert.equal(result.profiles.length,1);assert.equal(JSON.stringify(result).includes('PRIVATE'),false);
 const staticPlan=await vp.run({out:path.join(root,'static'),plan:true},loaded);assert.equal(staticPlan.status,'planned');
 await assert.rejects(vp.run({out:path.join(root,'no-authority'),endpoint:'http://127.0.0.1:1'},loaded));assert.equal(fs.existsSync(path.join(root,'no-authority')),false);
 const png=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(png);png.writeUInt32BE(1,16);png.writeUInt32BE(1,20);
 const good={send:async method=>method==='Page.captureScreenshot'?{data:png.toString('base64')}:{},evaluate:async expression=>expression=== '({width:innerWidth,height:innerHeight,devicePixelRatio})'?{width:360,height:640,devicePixelRatio:1}:{schemaVersion:1,source:expression.includes("source: 'CSS'")?'CSS':'DOM',truncated:false,nodes:[{address:'0',parent:null,tag:'div',id:'token=PRIVATE_FIXTURE',class:[],data:[],hidden:false,childCount:0,style:{display:'block'},rect:{x:0,y:0,width:1,height:1}}]},close:()=>{}};
 const collected=await vp.run({endpoint:'http://127.0.0.1:1',out:path.join(root,'safe'),testEnvironment:true,exclusiveMetrics:true},{...loaded,plan:{...plan,profiles:[plan.profiles[0]]}},{connect:async()=>good});assert.equal(collected.status,'complete');
 for(const file of ['phone-dom.json','phone-css.json']){const text=fs.readFileSync(path.join(root,'safe',file),'utf8');assert.equal(text.includes('PRIVATE_FIXTURE'),false);assert.ok(text.includes('[credential]'));}
});
